DFE-Digital/login.dfe.interactions

config/login.dfe.interactions.dev.json, src/index.js
add event listener on process for unhandled exceptions
=> add logLevel setting

package-lock.json, src/app/UsernamePassword/postUsernamePassword.js, src/app/UsernamePassword/views/index.ejs
Add option to cancel and go back to relying party
=> NSA-799 - Login unhappy pathes

src/app/DevLauncher/views/launchpad.ejs, src/app/UsernamePassword/getUsernamePassword.js, src/app/UsernamePassword/postUsernamePassword.js, src/app/UsernamePassword/views/index.ejs, src/app/rateLimit/index.js, src/index.js, test/UsernamePasswordTests/UsernamePassword.post.test.js
=> NSA-800 login error states

src/app/UsernamePassword/views/indexEas.ejs
- fixed the second login screen
=> Fix broken link

src/app/Content/index.js, src/app/Content/views/error.ejs, src/app/ResetPassword/getRequestPasswordReset.js, src/app/ResetPassword/postNewPassword.js, src/app/ResetPassword/postRequestPasswordReset.js, src/app/ResetPassword/views/request.ejs, src/app/UsernamePassword/postUsernamePassword.js, src/infrastructure/Clients/HotConfigClientAdapter.js, src/infrastructure/Users/DirectoriesApiUserAdapter.js, src/infrastructure/Users/StaticUserAdapter.js, test/ResetPasswordTests/getRequestPasswordReset.test.js, test/ResetPasswordTests/postNewPassword.test.js, test/ResetPasswordTests/postRequestPasswordReset.test.js, test/utils/index.js
@jamesmking Added default error page here as well
=> Nsa 1131 validate redirect uri

src/index.js
=> Remove rate limiter

src/app/UsernamePassword/getUsernamePassword.js, src/app/UsernamePassword/postUsernamePassword.js, src/app/migration/getMigratedUserDetails.js, src/app/migration/getMigrationIntro.js, src/app/migration/index.js, src/app/migration/views/userDetail.ejs, src/infrastructure/osa/OsaApiAdapter.js, src/infrastructure/osa/StaticOsaAdapter.js, test/UsernamePasswordTests/UsernamePassword.post.test.js
Also includes NSA-1286 intro content
=> NSA-1102 User profile Details

src/app/migration/getConfirmMigratedEmail.js, src/app/migration/getCreateNewPassword.js, src/app/migration/getMigratedEmail.js, src/app/migration/index.js, src/app/migration/postConfirmMigratedEmail.js, src/app/migration/postMigratedEmail.js, src/app/migration/views/confirmEmail.ejs, src/app/migration/views/createPassword.ejs, src/app/migration/views/email.ejs, src/app/migration/views/no-email.ejs, src/infrastructure/UserCodes/UserCodesApiAdapter.js, test/UserCodesTests/UserCodesApiAdapter.getCode.test.js, test/UserCodesTests/UserCodesApiAdapter.validateCode.test.js, test/migrationTests/getConfirmMigratedEmail.test.js, test/migrationTests/getCreateNewPassword.test.js, test/migrationTests/getMigrationEmail.test.js, test/migrationTests/getMigrationIntro.test.js, test/migrationTests/getMigrationUserDetails.test.js, test/migrationTests/postConfirmMigratedEmail.test.js, test/migrationTests/postMigratedEmail.test.js
Includes NSA-1301 as well for validating the user code
=> NSA-1288 change email code

package-lock.json, package.json, src/app/DevLauncher/views/launchpad.ejs, src/app/select-organisation/index.js, src/app/select-organisation/views/index.ejs, src/index.js, src/infrastructure/Organisations/OrganisationApiAdapter.js
Organisation API for accosiated-with-user
=> interaction UI for select-organisation

package-lock.json, package.json, src/app/UsernamePassword/postUsernamePassword.js, src/app/migration/postCreateNewPassword.js, src/infrastructure/Organisations/OrganisationApiAdapter.js, src/infrastructure/Services/ServicesApiAdapter.js, test/UsernamePasswordTests/UsernamePassword.post.test.js, test/migrationTests/postCreateNewPassword.test.js, test/services/ServicesApiAdapter.create.test.js
pick external identifiers off migratingUser
migrate off deprecated service/create
=> update to use new osaApi.auth method

src/app/migration/postCreateNewPassword.js, src/infrastructure/Organisations/OrganisationApiAdapter.js, src/infrastructure/Organisations/StaticOrganisationAdapter.js, test/migrationTests/postCreateNewPassword.test.js
* Add missing user/org/role mapping
* Refactor large action to smaller methods
* Refactor test mock setup
* Add more logging
=> NSA-1480 - Add user/org/role mapping

src/index.js
=> NSA-1572 - Remove sanitization of username and password fields

src/app/UsernamePassword/postUsernamePassword.js, src/app/migration/getServiceAccessDenied.js, src/app/migration/index.js, src/app/migration/views/serviceAccessDenied.ejs, test/UsernamePasswordTests/UsernamePassword.post.test.js
Otherwise they will encounter an error at the end of the process and be left in a broken state
=> NSA-1485 - Show page if user does not have access to service in SA

src/index.js
Fix apostrophe bug in email when resetting password
=> NSA-1604- Reset password sanitization

src/index.js
fixed sanitization bug that caused problems when changing name to contain special characters.
=> NSA-1607 Sanitization bug in edit details

src/index.js
givenName and familyName removed from sanitization exclusion as not required
=> Remove sanitization exclusion

package-lock.json, package.json, src/app/migration/workflow/index.js, src/infrastructure/access/api.js, src/infrastructure/access/index.js, src/infrastructure/access/static.js, test/ResetPasswordTests/postRequestPasswordReset.test.js, test/migrationTests/postCreateNewPassword.test.js
add user to service updated to use access api
=> Nsa 1703 access api

src/app/ResetPassword/postRequestPasswordReset.js, test/ResetPasswordTests/postRequestPasswordReset.test.js
fixed bug that caused two emails to be sent when resetting password if SA user and DSI user
=> NSA-1755- SA double reset password email bug

package-lock.json, package.json, src/app/UsernamePassword/postUsernamePassword.js, test/UsernamePasswordTests/UsernamePassword.post.test.js
send email to recognised SA email if attempt to sign in and not yet migrated
=> Unmigrated SA user email

src/app/UsernamePassword/postUsernamePassword.js, src/infrastructure/Users/DirectoriesApiUserAdapter.js
Bug caused email to be sent to a migrated SA user if they entered the correct email but incorrect password. Also fixed bug that caused service_home not to be returned. Links to NSA-1753
=> Nsa-1779 unmigrated sa user email

src/app/select-organisation/index.js, src/app/select-organisation/views/index.ejs
Display natural identifiers and address for org if exists
=> Nsa 1847 multiple org selection update

src/app/Content/index.js, src/index.js
Fallback to previous content page (now at /welcome) if service not configured in config
=> NSA-1883 - Redirect route to services

src/app/UsernamePassword/views/index.ejs, src/app/includes/helpdesk.ejs
Move T&C's above sign in button and remove reference to faqs
=> NSA-2074 - content update

src/app/select-organisation/index.js, src/app/select-organisation/views/index.ejs, src/infrastructure/Organisations/OrganisationApiAdapter.js, src/infrastructure/Organisations/StaticOrganisationAdapter.js
Show org status in select org page
=> NSA-2138- select org status

src/app/consent/grantAccess.js, src/app/consent/views/grantAccess.ejs
fix redirect bug in denied consent screen
=> update content for consent screen

package-lock.json, package.json, src/index.js
- Update express error handling to latest version
=> NSA-2495- cdn

src/app/UsernamePassword/getUsernamePassword.js
=> NSA-2790 Interaction redirect looses client-id in dev environment ( Service onboard fails in DEV )

src/app/consent/grantAccess.js, src/app/consent/selectOrganisation.js
=> NSA-2815-custom-claim

.vsts-ssp-ci.yml, azure/template-failover.json, azure/template.json, package.json, src/index.js, src/infrastructure/oidc/api.js
sibling pipeline and template for SSP devops - failover
=> NSA-3408 Failover pipeline work

src/app/Content/views/cookies.ejs, src/app/shared/layout.ejs
This reverts commit 0d8261d6b08588fd36acc8033b6b29d31ee94b9b, reversing
changes made to 072914321c95162c9df806d909843ee9955597c5.
=> Revert "Merge pull request #329 from DFE-Digital/feature/NSA-2990"

package.json, src/index.js
adds version number to healthcheck
=> pass through version number

package-lock.json, package.json, src/app/ResetPassword/postRequestPasswordReset.js
More logging for warning and errors has been added
=> PR-feature/4832-Add-logging-when-sending-an-email
